### ISSUE TITLE
Values are not encrypted on update

### ISSUE THREAD

**Issue by JoelBeerDe** [maize-tech/laravel-encryptable#12]
If I create a new model the data will be encrypted but when i update the same model the values are stored in plain text in the database.

I'm casting the values in the model as "Encryptable". It would be unfortunate if I had to manually encrypt the data when updating a model

**Comment by riccardodallavia** [comment]
Hi @JoelBeerDe 

Our package relies on attribute casting, which means that updates should be handled directly through eloquent models rather than direct SQL queries.

I've just done a bit of checking and everything seems to be working as expected on our end.

Could you please provide more details, such as the exact version of Laravel you're using and a snippet of your code where you perform the update to models?
